<?php

/*
 * libkinetic node ID interface
 *
 * This file is automatically generated by libkinetic-def
 */

declare(strict_types=1);

namespace SOFe\PostBox;

interface KineticIds{
	/**
	 * &lt;series&gt; "messages-byType" in &lt;KINETIC&gt;
	 */
	public const MESSAGES_BY_TYPE = "messages-byType";
}
