<?php

/*
 * libkinetic node ID interface
 *
 * This file is automatically generated by libkinetic-def
 */

declare(strict_types=1);

namespace SOFe\PostBox;

interface KineticIds{
	/**
	 * &lt;series&gt; "messages-byType" in &lt;KINETIC&gt;
	 */
	public const MESSAGES_BY_TYPE = "messages-byType";

	/**
	 * &lt;series&gt; "messages-byName" in &lt;KINETIC&gt;.&lt;series&gt;
	 */
	public const MESSAGES_BY_NAME = "messages-byName";

	/**
	 * &lt;series&gt; "messages-conversation" in &lt;KINETIC&gt;.&lt;series&gt;.&lt;series&gt;
	 */
	public const MESSAGES_CONVERSATION = "messages-conversation";
}
