<?php

/*
 * libglocal message ID constant file
 *
 * This file is automatically generated by libglocal-def
 */

declare(strict_types=1);

namespace SOFe\PostBox;

interface Lang{
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>PostBox</p>
	 * </blockquote>
	 */
	public const POSTBOX_KINETIC_MAIN_TITLE = "postbox.kinetic.main.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>View inbox</p>
	 * </blockquote>
	 */
	public const POSTBOX_KINETIC_MAIN_DESCRIPTION = "postbox.kinetic.main.description";
}
