<?php

/*
 * Auto-generated by libasynql-def
 * Created from mysql.sql, sqlite.sql
 */

declare(strict_types=1);

namespace SOFe\PostBox;

interface Queries{
	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:27
	 */
	public const POSTBOX_INIT_PLAYERS = "postbox.init.players";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:21
	 */
	public const POSTBOX_INIT_POSTS = "postbox.init.posts";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:83
	 *
	 * <h3>Variables</h3>
	 * - <code>:ids</code> int non-empty list, required in mysql.sql
	 */
	public const POSTBOX_MARK_AS_READ = "postbox.mark-as.read";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:89
	 *
	 * <h3>Variables</h3>
	 * - <code>:ids</code> int non-empty list, required in mysql.sql
	 */
	public const POSTBOX_MARK_AS_UNREAD = "postbox.mark-as.unread";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:53
	 *
	 * <h3>Variables</h3>
	 * - <code>:senderType</code> string, required in mysql.sql
	 * - <code>:name</code> string, required in mysql.sql
	 */
	public const POSTBOX_PLAYER_GROUP_BY_SENDER_NAME = "postbox.player.group-by.sender-name";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:44
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in mysql.sql
	 */
	public const POSTBOX_PLAYER_GROUP_BY_SENDER_TYPE = "postbox.player.group-by.sender-type";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:65
	 *
	 * <h3>Variables</h3>
	 * - <code>:senderName</code> string, required in mysql.sql
	 * - <code>:senderType</code> string, required in mysql.sql
	 * - <code>:name</code> string, required in mysql.sql
	 */
	public const POSTBOX_PLAYER_LIST_SENDER_TYPE_NAME = "postbox.player.list.sender-type-name";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:75
	 */
	public const POSTBOX_PLAYER_SEARCH = "postbox.player.search";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:35
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in mysql.sql
	 */
	public const POSTBOX_PLAYER_TOUCH = "postbox.player.touch";

}
