<?php

/*
 * Auto-generated by libasynql-def
 * Created from mysql.sql, sqlite.sql
 */

declare(strict_types=1);

namespace SOFe\PostBox;

interface Queries{
	/**
	 * <code>postbox.init.players</code>
	 *
	 * Defined in mysql.sql:22, sqlite.sql:21
	 */
	public const POSTBOX_INIT_PLAYERS = "postbox.init.players";

	/**
	 * <code>postbox.init.posts</code>
	 *
	 * Defined in mysql.sql:16, sqlite.sql:15
	 */
	public const POSTBOX_INIT_POSTS = "postbox.init.posts";

	/**
	 * <code>postbox.mark-read</code>
	 *
	 * Defined in mysql.sql:84, sqlite.sql:91
	 *
	 * Variables:
	 * - <code>:username</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:ids</code> int non-empty list, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_MARK_READ = "postbox.mark-read";

	/**
	 * <code>postbox.player.find.by-name</code>
	 *
	 * Defined in mysql.sql:101, sqlite.sql:108
	 *
	 * Variables:
	 * - <code>:name</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_PLAYER_FIND_BY_NAME = "postbox.player.find.by-name";

	/**
	 * <code>postbox.player.touch</code>
	 *
	 * Defined in mysql.sql:108, sqlite.sql:114
	 *
	 * Variables:
	 * - <code>:name</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_PLAYER_TOUCH = "postbox.player.touch";

	/**
	 * <code>postbox.send-message</code>
	 *
	 * Defined in mysql.sql:93, sqlite.sql:100
	 *
	 * Variables:
	 * - <code>:senderName</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:senderType</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:recipient</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:priority</code> int, optional in mysql.sql, sqlite.sql
	 * - <code>:message</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_SEND_MESSAGE = "postbox.send-message";

	/**
	 * <code>postbox.unread.by-type-name</code>
	 *
	 * Defined in mysql.sql:76, sqlite.sql:83
	 *
	 * Variables:
	 * - <code>:username</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:sender</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:type</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_UNREAD_BY_TYPE_NAME = "postbox.unread.by-type-name";

	/**
	 * <code>postbox.unread.by-type.collapse</code>
	 *
	 * Defined in mysql.sql:63, sqlite.sql:68
	 *
	 * Variables:
	 * - <code>:username</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:type</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_UNREAD_BY_TYPE_COLLAPSE = "postbox.unread.by-type.collapse";

	/**
	 * <code>postbox.unread.by-type.expanded</code>
	 *
	 * Defined in mysql.sql:50, sqlite.sql:53
	 *
	 * Variables:
	 * - <code>:username</code> string, required in mysql.sql, sqlite.sql
	 * - <code>:type</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_UNREAD_BY_TYPE_EXPANDED = "postbox.unread.by-type.expanded";

	/**
	 * <code>postbox.unread.dashboard</code>
	 *
	 * Defined in mysql.sql:37, sqlite.sql:38
	 *
	 * Variables:
	 * - <code>:username</code> string, required in mysql.sql, sqlite.sql
	 */
	public const POSTBOX_UNREAD_DASHBOARD = "postbox.unread.dashboard";

}
