projects:
  PostBox:
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.1
        epitope: ".random"
      - src: poggit/libasynql/libasynql
        version: ^3.0
        epitope: ".random"
      - src: SOF3/libglocal/libglocal
        version: ^0.2
        epitope: ".random"
      - src: SOF3/libkinetic/libkinetic
        version: ^0.0.2
        branch: "*"
        epitope: ".random"
